version: "3.7"

services:
  db:
    build:
      context: ./AccountMicroService/
      dockerfile: Dockerfile-DB
    container_name: ms_practice_postgres
    # environment:
    #   POSTGRES_DB: user_test_table
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    networks:
      inner:
        aliases:
          - db
    deploy:
      constraints:
        - node.role == worker
  account:
    # restart: always
    build: 
      context: ./AccountMicroService/
      dockerfile: Dockerfile
    container_name: ms_practice_account_service
    depends_on: 
      - db
    ports:
      - "50051:50051"
    command: 
      - /bin/sh
      - -c
      - |
          python /code/AccountRPCServer.py
    volumes:
      - type: bind
        source: ./AccountMicroService/
        target: /code/      
    networks:
      inner:
        aliases:
          - account
      outter:
        aliases:
          - account
    deploy:
      constraints:
        - node.role = manager    
  tester:
    build:
      context: ./TestService/AccountTest/
      dockerfile: Dockerfile
    container_name: ms_practice_account_tester
    depends_on:
      - account
    volumes:
      - type: bind
        source: ./TestService/AccountTest/
        target: /code/      
    command: python /code/account_rpc_test.py
    networks: 
      outter:
        aliases:
          - tester
networks:
  inner:
  outter:
volumes:
  database:
